### ISSUE TITLE
Collab svc - end session bugs (and related)

### ISSUE THREAD

**Issue by lynnetteeee** [CS3219-AY2425S1/cs3219-ay2425s1-project-g01#56]
- integrate w db for sessioning (@smolegz)
- end session - deletes/removes record (so that subsequent matches between the same user will create a new session and get the correct question) (@lynnetteeee can do after db implemented)

**Comment by smolegz** [comment]
Re-verify point 2 after merging #66 , may not be needed

**Comment by smolegz** [comment]
Closing this
