### ISSUE TITLE
ADD/EDIT modal fixes

### ISSUE THREAD

**Issue by lynnetteeee** [CS3219-AY2425S1/cs3219-ay2425s1-project-g01#95]
1. sussy outline at the bottom of the page (and outline of ADD/EDIT modals)
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/5c704b56-1032-40d8-bbc6-79b9efae67cf">

2. this scroll nonsense (hopefully the last scroll problem HAHAH)
<img width="955" alt="image" src="https://github.com/user-attachments/assets/2949064d-82be-4cdf-b95b-7164d144db9b">

**Comment by Teeesa7** [comment]
#97 fixes
